### ISSUE TITLE
Align following a property with SPARQL property path specs

### ISSUE THREAD

**Issue by ktk** [rdf2h/rdf2h#13]
I think it would make sense to align the syntax for following properties with SPARQL property paths.

As an example, `<-` should be replaced with `^`.

Docs: https://www.w3.org/TR/sparql11-query/#propertypaths

**Comment by retog** [comment]
`^` prefix for inverse properties is now supported (old syntax is also still supported). I think several aspects of property path syntax are not applicable or useful in rdf2h, please open individual issues for every change you would like to see.

**Comment by retog** [comment]
The test is actually failing (what are tests good if I ignore the result).

The '^'-syntax conflicts with mustache `Inverted Sections` syntax.

**Comment by retog** [comment]
Closing issue as this conflicts with mustache syntax
