### ISSUE TITLE
Debug mode

### ISSUE THREAD

**Issue by ktk** [rdf2h/rdf2h#3]
Is there a debug mode I can enable if we can't figure out why a matcher is not working?

My colleague got it working when the data is loaded within the HTML file but as soon as it is coming from SPARQL it just outputs the text from the default matcher and that's it.

**Comment by retog** [comment]
I cleaned up logging-output, by default it desn't say a lot, see more debug output invoke RDF2h.logger.setLevel(Logger.DEBUG) or even RDF2h.logger.setLevel(Logger.TRACE). Please see if this allows you to debug your problem.

**Comment by retog** [comment]
closing the issue, please reopen if somethin is missing.
